name: digital_eye
description: Assistive vision app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.3
  flutter_tts: ^4.2.3
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  battery_plus: ^6.0.2
  url_launcher: ^6.2.5
  google_mlkit_text_recognition: ^0.14.0
  google_mlkit_object_detection: ^0.14.0
  speech_to_text: ^7.3.0
  intl: ^0.19.0
  lottie: ^3.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/digital_eye.png



flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/eye.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/eye.png"